Engine configuration@include model versioning engine configuration
fintual/gemaker pull request #3
Opened 2021-06-15 04:02 UTC by abannura

**Contexto**

Para evitar que tengamos que configurar a mano el engine `PapertrailConfig` en los nuevos engines que construyamos usando `gemaker`, extendí esté último. Se agregan los archivos adicionales necesarios, y se hace `require` de estos donde corresponda.

**QA**

Correr el comando `bundle exec gemaker new my_engine` y revisar lo siguiente:
- Se crea el archivo `engines/my_engine/lib/my_engine/papertrail_config.rb` y se hace require de este en el archivo `engines/my_engine/lib/my_engine/engine.rb`
- Se crea el archivo `engines/my_engine/lib/my_engine/paper_trail_configuration.rb` y se hace require de este en el archivo `engines/my_engine/lib/my_engine.rb`
- Se hace require del nuevo engine `PapertrailConfig` en el archivo `engines/my_engine/lib/my_engine.rb`
- Se incluye `PapertrailConfig::ApplicationRecordConcern` en el `ApplicationRecord` del engine
- Se incluye engine `PapertrailConfig` en el `Gemfile`

Revisar que los archivos se crean con los nombres correctos, y con el nombre del módulo correcto (i.e. que correspondan con el nombre del engine)

Lo puedo hacer yo si les parece bien.

2021-06-15 04:06 UTC, abannura commented
Duda, debería cambiarle la versión a la gema? Patch o Minor?

2021-06-15 06:05 UTC, danieldt commented
> Duda, debería cambiarle la versión a la gema? Patch o Minor?

La otra vez que hice un fix, no le subí la versión. Yo creo que lo dejaría así no más por ahora, ya que la tenemos así en nuestro Gemfile: `gem "fintual-gemaker", github: "fintual/gemaker", branch: "main"`.

Naturalmente, otros clientes de esta gema no pensarían igual, pero dudo que alguien más la esté usando.

2021-06-15 06:07 UTC, danieldt requested changes

2021-06-15 06:07 UTC, danieldt commented on lib/gemaker/templates/engine/Gemfile
> +gem "papertrail_config", path: "../papertrail_config"
Tengo la duda acá, si se podrá hacer de forma más dinámica.
Pensando en no hardcodear el `../`, si es que, como en nuestro caso, queremos tener engines dentro de carpetas por categoría.

Sino, lo dejaría así no más por ahora

2021-06-15 12:19 UTC, abannura commented on lib/gemaker/templates/engine/Gemfile
> +gem "papertrail_config", path: "../papertrail_config"
Buena! Lo había pensado, y me tinca ver si podemos tenerlo

Quizás podríamos pasarle un flag al comando del gemaker para que decida si agregar o no un extra "../"

También podríamos trabajar con el path absoluto en vez de relativo

Voy a probar y te cuento!

2021-06-15 20:18 UTC, danieldt requested changes

2021-06-15 20:18 UTC, danieldt commented on lib/gemaker/templates/engine/Gemfile
> +].first
Joven, revisé esto y creo que se puede acortar un poquito para dejarlo más simple.
Aparte, me parece que `Dir.glob` me dice más que `Dir[]`, por lo que creo que queda más claro.

```suggestion
papertrail_config_path = Dir.glob(File.join(__FILE__[/^.*engines/], "**", "papertrail_config"))[0]
```

Qué opinas?

2021-06-15 20:40 UTC, abannura commented on lib/gemaker/templates/engine/Gemfile
> +].first
Cambiado! La verdad es que no soy fan del `[0]` vs hacer `first`, pero me gusta que quede en 1 línea (y con el slice queda en 99 chars jaja)

2021-06-15 20:44 UTC, danieldt commented on lib/gemaker/templates/engine/Gemfile
> +].first
Jajjaa, sí. Fue solo para que quedara en una línea y fuera más fácil de leer 😬

2021-06-15 20:44 UTC, danieldt approved these changes

2021-06-18 18:22 UTC, juanweitz approved these changes
@danieldt @abannura Con los cambios de directorio que hace daniel, como quedaria esto?

2021-06-18 18:23 UTC, abannura commented
> @danieldt @abannura Con los cambios de directorio que hace daniel, como quedaria esto?

2021-06-18 18:24 UTC, danieldt commented
> @danieldt @abannura Con los cambios de directorio que hace daniel, como quedaria esto?

Hay que probarlo y probablemente hacer algunos cambios.
Yo lo pruebo una vez termine con los directorios, me lo anotaré

2021-06-18 18:25 UTC, abannura commented
Entiendo que están considerados. Por eso fue el comentario de @danieldt, de hacer que el `gem papertrail_config` supiera que puede tener que buscar en `../papertrail_config` o en `../../papertrail_config`

2021-06-18 18:26 UTC, danieldt commented
> Entiendo que están considerados. Por eso fue el comentario de @danieldt, de hacer que el `gem papertrail_config` supiera que puede tener que buscar en `../papertrail_config` o en `../../papertrail_config`

Me tinca que pueden haber más detalles fuera de papertrail, pero es tema de otro PR

2021-06-18 18:27 UTC, abannura commented
> > Entiendo que están considerados. Por eso fue el comentario de @danieldt, de hacer que el `gem papertrail_config` supiera que puede tener que buscar en `../papertrail_config` o en `../../papertrail_config`
> 
> Me tinca que pueden haber más detalles fuera de papertrail, pero es tema de otro PR

Ahh claro, podrían haber más cosas por el tema de anidar los engines en categorías

2021-06-18 20:00 UTC, merged